name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * *


jobs:
  build_linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: false
      
      - uses: mymindstorm/setup-emsdk@v14
      
      - uses: actions/checkout@v4

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libglu1-mesa-dev mesa-common-dev xorg-dev libasound2-dev
          version: 1.2
     
      - name: Build Sokol libs
        working-directory: ./source/sokol
        run: |
          ./build_clibs_linux.sh
          ./build_clibs_wasm.sh

      - name: Build desktop
        run: ./build_desktop.sh

      - name: Build web
        run: ./build_web.sh

  build_macos:
    name: MacOS
    strategy:
      matrix:
        os: [macos-15-intel, macos-15]
    runs-on: ${{matrix.os}}
    steps:
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: false
      
      - uses: mymindstorm/setup-emsdk@v14

      - uses: actions/checkout@v4

      - name: Build Sokol libs
        working-directory: ./source/sokol
        run: |
          ./build_clibs_macos.sh
          ./build_clibs_macos_dylib.sh
          ./build_clibs_wasm.sh

      - name: Build desktop
        run: ./build_desktop.sh

      - name: Build web
        run: ./build_web.sh

  build_windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: false

      - uses: mymindstorm/setup-emsdk@v14

      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build Sokol libs
        working-directory: .\source\sokol
        run: |
          .\build_clibs_windows.cmd
          .\build_clibs_wasm.bat

      - name: Build desktop
        run: .\build_desktop.bat

      - name: Build web
        run: .\build_web.bat
